name: Build and Release
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_commit_msg.outputs.skip }}
    steps:
      - name: Check commit message
        id: check_commit_msg
        run: |
          if [[ "${{ github.event.head_commit.message }}" == rel* ]]; then
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            echo "Commit message does not start with 'rel', skipping build."
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.skip == 'false'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: cp313
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Package code and Python environment
        run: |
          # Ensure the package directory is clean
          rm -rf package
          mkdir -p package
          # Copy code files, excluding the package directory itself
          shopt -s extglob
          cp -r !(package) package/
          # Copy Python executable and libraries
          ${{ steps.cp313.outputs.python-path }} > python_path.txt
          set /p PYTHON_PATH=<python_path.txt
          xcopy "%PYTHON_PATH%\.." package\python_env\ /E /H /C /I
          # Create a cmd script to start the program
          echo "@echo off" > package\start.cmd
          echo "python_env\\python.exe main.py" >> package\start.cmd
          echo "pause" >> package\start.cmd

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-code
          path: package/

      - name: Clean up
        run: |
          rm -rf package/
          echo "Cleaned up build artifacts."

  release:
    needs: [check, build]
    if: needs.check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-code
          path: package/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: package/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}